Leaked host key check: Avoid false positives from FIPS mode
github/backup-utils pull request #748
Opened 2021-06-18 01:58 UTC by mumfy

Enabling FIPS (Federal Information Processing Standards) mode on the backup server
may cause `ssh-keygen`'s MD5-based fingerprint generation to fail.

A "fingerprint_one_key: sshkey_fingerprint failed" message is written to stderr
whilst nothing is written to stdout, so the `fingerprint` variable is blank.

A grep search for an empty string succeeds, so `ghe-detect-leaked-ssh-keys`
reports that a leaked hostkey was found.

This change detects this condition and the final output says if the hostkey check was skipped.

2021-06-18 02:32 UTC, sonialey25 requested changes
yo

2021-06-22 18:06 UTC, bwestover approved these changes
I like this general solution. Thanks for the write up and the fix :+1:

2021-06-30 02:58 UTC, djdefi commented
The macos CI failure here is a known failure, so I think this is good to merge @mumfy

2021-07-06 00:39 UTC, merged

2021-07-06 17:05 UTC, Dwayne227 commented
Give me min i will bite in my toung

On Mon, Jul 5, 2021, 8:06 PM Dwayne Garmon ***@***.***>
wrote:

>
> On Mon, Jul 5, 2021, 7:39 PM Andy J ***@***.***> wrote:
>
>> Merged #748 <https://github.com/github/backup-utils/pull/748> into
>> master.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/github/backup-utils/pull/748#event-4980425754>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AUXBR7CSZTVFYCO27L3CAELTWJGD5ANCNFSM464YCPAQ>
>> .
>>
>

2021-08-08 00:08 UTC, MintThitiratChamnan reviewed
Up date

2021-09-08 10:08 UTC, Kittenmoon21 reviewed
share/github-backup-utils/ghe-detect-leaked-ssh-keys

2021-09-08 10:09 UTC, Kittenmoon21 commented
looks good

2021-09-08 10:09 UTC, Kittenmoon21 commented
From aeb986586fa926dbebebc70a07dfc801784dee8f Mon Sep 17 00:00:00 2001 From: Andy Jones <mumfy@github.com> Date: Fri, 18 Jun 2021 11:39:52 +1000 Subject: [PATCH] Leaked host key check: Avoid false positives from FIPS mode Enabling FIPS (Federal Information Processing Standards) mode may cause ssh-keygen's MD5-based fingerprint generation to fail, resulting in a message on stderr and a blank fingerprint string. A grep search for an empty string succeeds so a blank fingerprint is reported as a leaked host key. --- share/github-backup-utils/ghe-detect-leaked-ssh-keys | 11 +++++++++-- 1 file changed, 9 insertions(+), 2 deletions(-) diff --git a/share/github-backup-utils/ghe-detect-leaked-ssh-keys b/share/github-backup-utils/ghe-detect-leaked-ssh-keys index 75b65a98f..79978ddf0 100755 --- a/share/github-backup-utils/ghe-detect-leaked-ssh-keys +++ b/share/github-backup-utils/ghe-detect-leaked-ssh-keys @@ -69,6 +69,7 @@ if [ -L "$GHE_DATA_DIR/current" ]; then fi leaked_keys_found=false +leaked_keys_skippedcheck=false current_bkup=false for tar_file in $ssh_tars; do for key in $keys; do @@ -79,7 +80,9 @@ for tar_file in $ssh_tars; do else fingerprint=$(ssh-keygen -lf $TEMPDIR/$key | cut -d ' ' -f 2) fi - if echo "$FINGERPRINT_BLACKLIST" | grep -q "$fingerprint"; then + if [ -z "$fingerprint" ]; then + leaked_keys_skippedcheck=true + elif echo "$FINGERPRINT_BLACKLIST" | grep -q "$fingerprint"; then leaked_keys_found=true if [ "$current_dir" == "$(dirname "$tar_file")" ]; then current_bkup=true @@ -126,7 +129,11 @@ if $leaked_keys_found; then echo fi else - echo "* No leaked keys found" + if $leaked_keys_skippedcheck; then + echo "* No result - check not performed since host key fingerprint was empty" + else + echo "* No leaked keys found" + fi fi # Cleanup temp dir

2021-09-08 10:10 UTC, Kittenmoon21 reviewed
mumfy/leaked-key-check-improvement
nice

2021-09-11 11:03 UTC, rigrell28 commented
Ok

2021-09-11 11:04 UTC, rigrell28 commented
Oo

2021-09-11 11:04 UTC, rigrell28 reviewed
Ok

2021-09-11 11:41 UTC, Shazcarrera96 commented
GPERROR

On Sat, Sep 11, 2021, 7:05 PM Romel Rellon ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Ok
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/backup-utils/pull/748#pullrequestreview-751910509>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVDKLG3XM73V6WT6NTIOJWLUBMZXPANCNFSM464YCPAQ>
> .
>